myrates/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("services/",views.OurServices.as_view(),name="services"),
    path("add_services/",views.ServiceAdd.as_view(),name="add_services"),
    path("service_details/<int:servid>",views.ServiceDetails.as_view(),name="service_details"),
    path("service_price/<int:servid>/<int:townid>",views.ServicePrice.as_view(),name="service_price"),
    path("edit_services/<int:servid>",views.ServiceEdit.as_view(),name="edit_services"),
    path("delete_service/<int:servid>",views.ServiceDelete.as_view(),name="delete_service"),
    path("myapplications/",views.ApplicationsListing.as_view(),name="myapplications"),
    path("application_details/<int:aplid>",views.ApplicationDetails.as_view(),name="details"),
    path("applicationsreceived/",views.ApplicationsReceived.as_view(),name="received"),
    path("performance/",views.Dashboard.as_view(),name="performance"),
    path("companyProfile/",views.CompanyDetails.as_view(),name="companyProfile"),
    # requirements
    path("requirements/",views.Requirements.as_view(),name="requirements"),
    # pricing
    path("pricing/",views.Pricing.as_view(),name="pricing"),
    path("payments/",views.PaymentUpdates.as_view(),name="payments"),
    path("application_ui/",views.ApplicationUI.as_view(),name = "application")
] 

myrates/myrates/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("accounts/", include("accounts.urls",namespace="accounts")),
    path("core/", include("core.urls", namespace="core")),
]# + \
#static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #+ \
# static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

myrates/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Towns(models.Model):
    county = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    municipality = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Services(models.Model):
    title        = models.CharField(max_length=100)
    description  = models.TextField()
    requirements = models.TextField()
    
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class ServiceRequirements(models.Model):
    requirement = models.TextField()
    service     = models.ForeignKey(Services, on_delete=models.CASCADE)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    
class Prices(models.Model):
    service    = models.ForeignKey(Services, on_delete=models.CASCADE)
    town       = models.ForeignKey(Towns, on_delete=models.CASCADE)
    amount     = models.DecimalField(max_digits=10, decimal_places=2)
    approved   = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    
    
class ApplicationRecords(models.Model):
    user                 = models.ForeignKey(User, on_delete=models.CASCADE)
    service              = models.ForeignKey(Services, on_delete=models.CASCADE)
    amount               = models.DecimalField(max_digits=10, decimal_places=2)
    # balance              = models.DecimalField(max_digits=10, decimal_places=2)
    paymentStatus        = models.TextField(max_length=30,choices=[('Pending','Pending'),('Approved','Approved'),('Unpaid','Unpaid'),('Declined','Declined')])
    transactioncode      = models.CharField(max_length=100)
    resolution           = models.TextField(max_length=100,choices=[('New','New'),('Queued','Queued'),('Closed','Closed')])
    remarks              = models.TextField(null=True)
    filesUploaded        = models.CharField(null=True,max_length=1024)
    invoice              = models.CharField(null=True,max_length=1024)
    created_at           = models.DateTimeField(auto_now_add=True)
    updated_at           = models.DateTimeField(auto_now=True)
    
    # def __str__(self):
    #     return self.service
    
    

class ApplicationFiles(models.Model):
    application = models.ForeignKey(ApplicationRecords, on_delete=models.CASCADE)
    file        = models.FileField( upload_to='files/')
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.file
    
    
class CompanyProfile(models.Model):
    name        = models.CharField(max_length=100)
    address     = models.TextField()
    mobile      = models.CharField(max_length=12)
    email       = models.EmailField()
    paybill     = models.CharField(max_length=100)
    accountno   = models.CharField(max_length=100)
    tillno      = models.CharField(max_length=100)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    

class MpesaTransactions(models.Model):
    phone           = models.CharField(max_length=12)
    amount          = models.DecimalField(max_digits=10, decimal_places=2)
    transction_code = models.CharField(max_length=100,unique=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

class Notification(models.Model):
    title       = models.CharField(max_length=100)
    description = models.TextField()
    type        = models.CharField(max_length=100,choices=[('New','New'),('Queued','Queued'),('Closed','Closed')])
    sender      = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

myrates/core/views.py
import os
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin


from accounts.models import Profile
from .models import (
    ApplicationFiles,
    ApplicationRecords,
    CompanyProfile,
    Services,
    ServiceRequirements,
    Towns,
    Prices,
)
from django.core.files.storage import FileSystemStorage

# Create your views here.


class Dashboard(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        enquiries = ApplicationRecords.objects.all()
        context = {
            "total_enquiries": enquiries.count(),
            "new": enquiries.filter(resolution="New").count(),
            "queued": enquiries.filter(resolution="Queued").count(),
            "closed": enquiries.filter(resolution="Closed").count(),
        }
        return render(request, "core/dashboard.html", context)


class Requirements(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def post(self, request):
        requirements = request.POST
        requirement = requirements["requirement"]
        requirement = ServiceRequirements(requirement=requirement)
        requirement.save()
        return redirect("core:add_services")


class OurServices(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        services = Services.objects.all()
        context = {"services": services}
        return render(request, "core/services.html", context)


class ServiceAdd(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        requirements = ServiceRequirements.objects.all()
        context = {"requirements": requirements}
        return render(request, "core/pages/new_service.html", context)

    def post(self, request):
        try:
            service_details = request.POST
            title = service_details["title"]
            description = service_details["description"]
            requirements = service_details["requirement"]
            service = Services(
                title=title, description=description, requirements=requirements
            )
            service.save()
            messages.success(request, "Service added successfully!")
            return redirect("core:services")
        except Exception as e:
            messages.error(request, f"Something went wrong! {e}")
            return render(request, "core/pages/new_service.html")


class ServiceDetails(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid):
        service = Services.objects.get(id=servid)
        towns = Towns.objects.all()
        companyinfo = CompanyProfile.objects.all().last()
        context = {"service": service, "towns": towns, "companyinfo": companyinfo}
        return render(request, "core/pages/service_details.html", context)

    def post(self, request, servid):
        try:
            if request.POST["formid"] == "apply":

                uploadedfiles = request.FILES
                fs = FileSystemStorage()
                uploaded_file_urls = []
                for file in uploadedfiles.keys():
                    file_uploaded = uploadedfiles[file]
                    fileName = f"{file}_{request.user.id}_{servid}_{file_uploaded.name}"
                    fs.save(fileName, file_uploaded)
                    uploaded_file_urls.append(fileName)
                apl = ApplicationRecords(
                    user=User.objects.get(id=request.user.id),
                    service=Services.objects.get(id=servid),
                    amount=request.POST["amount"],
                    paymentStatus="Pending",
                    resolution="New",
                    transactioncode=request.POST["transactioncode"],
                    filesUploaded=",".join(uploaded_file_urls),
                )
                apl.save()
                messages.success(request, "Application submitted successfully!")
                return redirect("core:services")
            elif request.POST["formid"] == "paymentupdate":
                application = ApplicationRecords.objects.get(
                    id=request.POST["applicationid"]
                )
                application.amount = request.POST["amount"]
                application.transactioncode = request.POST["transactioncode"]
                application.save()
                messages.success(request, "Payment details updated successfully!")
                return redirect("core:details", aplid=application.id)
        except Exception as e:
            messages.error(self.request, f"An error occured!{e}")
            return redirect("core:services")


class ServiceEdit(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid):
        service = Services.objects.get(id=servid)
        context = {"service": service}
        return render(request, "core/pages/edit_services.html", context)

    def post(self, request, servid):
        try:
            service_details = request.POST
            title = service_details["title"]
            description = service_details["description"]
            service = Services.objects.get(id=servid)
            service.title = title
            service.description = description
            service.save()
            messages.success(request, "Service updated successfully!")
            return redirect("core:services")
        except Exception as e:
            messages.error(request, f"Something went wrong! {e}")
            return redirect("core:services")


class ServiceDelete(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid):
        try:
            service = Services.objects.get(id=servid)
            service.delete()
            messages.success(request, f"Service delete successfully!")
            return redirect("core:services")
        except Exception as e:
            messages.error(request, f"Error occured!,{e}")
            return redirect("core:services")


class ServicePrice(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid, townid):
        try:
            service = Services.objects.get(id=servid)
            town = Towns.objects.get(id=townid)
            price = get_object_or_404(Prices, service=service, town=town)
            context = {"price": price.amount}
            return JsonResponse(context)
        except Exception as e:
            context = {"message": f"Error occured!,{e}"}
            return JsonResponse(context)


class ApplicationsListing(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        try:
            applications = ApplicationRecords.objects.filter(user=request.user)
            if request.user.is_staff:
                applications = ApplicationRecords.objects.all()
            new = applications.filter(paymentStatus="Pending", resolution="New")
            onque = applications.filter(paymentStatus="Paid", resolution="Queued")
            closed = applications.filter(paymentStatus="Paid", resolution="Closed")
            context = {"new": new, "onque": onque, "closed": closed}
            return render(request, "core/myapplications.html", context)
        except Exception as e:
            messages.error(request, f"Error occured!,{e}")
            return HttpResponse(f"Something went wrong! ,{e}")


class ApplicationDetails(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, aplid):
        application = ApplicationRecords.objects.get(id=aplid)
        profile = Profile.objects.get(user=request.user)
        companyDetails = CompanyProfile.objects.all().last()
        context = {
            "application": application,
            "companyDetails": companyDetails,
            "profile": profile,
        }
        return render(request, "core/application_details.html", context)

    def post(self, request, aplid):
        application = ApplicationRecords.objects.get(id=aplid)
        formdetails = request.POST
        if formdetails["resolution"] in ["Closed", "Queued"]:
            application.resolution = formdetails["resolution"]
            application.paymentStatus = "Paid"
            if "invoice" in request.FILES.keys():
                # upload invoice
                fs = FileSystemStorage()
                file_uploaded = request.FILES["invoice"]
                fileName = f"INVOICE_{request.user.id}_{aplid}_{file_uploaded.name}"
                fs.save(fileName, file_uploaded)
                application.invoice = fileName
            application.save()
            messages.success(request, "Application progress updated successfully!")
            if application.resolution == "Closed":
                # send email to user
                
                messages.success(request, "Application closed successfully!")
            return redirect("core:myapplications")
        else:
            messages.error(request, "Something went wrong!")
            return redirect("core:details", aplid=aplid)


class ApplicationsReceived(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        return render(request, "core/applicationsreceived.html")


class Pricing(LoginRequiredMixin, View):

myrates/templates/core/modals/addrequirementmodal.html
<div class="modal fade" id="addreq" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New Requirement</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{% url "core:requirements" %}" method="post">
          {% csrf_token %}
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">Requirement</label>
            <div class="col-md-8 col-lg-9">
              <input name="requirement" type="text" class="form-control" id="title" value="" />
            </div>
          </div>
          <div class="mb-3">
            <button class="btn btn-primary" type="submit"><i class="bi bi-plus"></i>Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Basic Modal -->

myrates/templates/core/modals/deleteservicemodal.html
<div class="modal fade" id="delete-serv" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete {{ service.title }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="delete-warning">
          <h3 class="warningtitle">Are you sure you want to remove this Service?</h3>
          <p class="">This action is irreversable!</p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal" aria-label="Close" data-bs-target="#delete-serv">No</button>
        <a href="{% url 'core:delete_service' service.id %}" type="button" class="btn btn-danger">Yes</a>
      </div>
    </div>
  </div>
</div>

myrates/templates/core/modals/newTown.html
<div class="modal fade" id="addTown" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New Town </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{% url "core:pricing" %}" method="post">
          {% csrf_token %}
          <input name="formid" type="text" class="form-control" id="title" value="towns" hidden />
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">County</label>
            <div class="col-md-8 col-lg-9">
              <input name="county" type="text" class="form-control" id="county" value="" />
            </div>
          </div>
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">Town</label>
            <div class="col-md-8 col-lg-9">
              <input name="town" type="text" class="form-control" id="town" value="" />
            </div>
          </div>
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">Municipality</label>
            <div class="col-md-8 col-lg-9">
              <input name="municipality" type="text" class="form-control" id="town" value="" />
            </div>
          </div>
          <div class="mb-3">
            <button name="addTown" class="btn btn-primary" type="submit"><i class="bi bi-plus"></i>Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Basic Modal -->

myrates/templates/core/modals/priceSetup-delete.html
<div class="modal fade" id="deletePrice-{{ price.id }}" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete {{ price.service }} at {{ price.town.town}} town for sh{{ price.amount }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <div class="delete-warning text-center">
          <h1><i class="bi bi-exclamation-triangle-fill"></i></h1>
          <h3 class="warningtitle">Are you sure you want to remove this price information?</h3>
          <p class="">This action is irreversable!</p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal" aria-label="Close" data-bs-target="#delete-serv">No</button>
        <form action="" method="post">
          {% csrf_token %}
          <input type="hidden" name="formid" value="priceDelete">
          <input type="hidden" name="priceid" value="{{ price.id }}">
          <button type="submit" class="btn btn-danger">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>

myrates/templates/core/modals/priceSetup-edit.html
<div class="modal fade" id="editPrice-{{ price.id }}" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Price Modification</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{% url 'core:pricing' %}" method="post">
          {% csrf_token %}
          <input name="formid" type="text" class="form-control" id="title" value="priceEdit" hidden />
          <input name="priceid" type="text" class="form-control" id="title" value="{{price.id}}" hidden />
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">Service</label>
            <div class="col-md-8 col-lg-9">
              <!-- <input name="Service" type="text" class="form-control" id="county" value="" /> -->
              <select name="service" id="service" class="form-select form-control">
                {% for service in services %}
                  {% if service.id == price.service.id %}
                    <option value="{{ service.id }}" selected>{{ service.title }}</option>
                  {% else %}
                    <option value="{{ service.id }}">{{ service.title }}</option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">Town</label>
            <div class="col-md-8 col-lg-9">
              <select name="town" id="" class="form-select form-control">
                <option value="">Select Town</option>
                {% for town in towns %}
                  {% if town.id == price.town.id %}
                    <option value="{{ town.id }}" selected>{{ town.town }}</option>
                    {% else %}
                    <option value="{{ town.id }}">{{ town.town }}</option>
                    {% endif %}
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label for="email" class="col-md-4 col-lg-3 col-form-label">Amount</label>
            <div class="col-md-8 col-lg-9">
              <input name="amount" type="number" class="form-control" id="amount" value="" />
            </div>
          </div>
          <div class="mb-3">
            <button name="addTown" class="btn btn-primary" type="submit"><i class="bi bi-plus"></i>Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Basic Modal -->

myrates/templates/core/modals/priceSetup.html
<div class="modal fade" id="newPrice" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Price Setup</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url "core:pricing" %}" method="post">
            {% csrf_token %}
            <input name="formid" type="text" class="form-control" id="title" value="pricing" hidden />
            <div class="row mb-3">
              <label for="email" class="col-md-4 col-lg-3 col-form-label">Service</label>
              <div class="col-md-8 col-lg-9">
                <!--<input name="Service" type="text" class="form-control" id="county" value="" /> -->
                <select name="service" id="service" class="form-select form-control">
                  <option value="">Select Service</option>
                  {% for service in services %}
                    <option value="{{service.id}}">{{service.title}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="row mb-3">
              <label for="email" class="col-md-4 col-lg-3 col-form-label">Town</label>
              <div class="col-md-8 col-lg-9">
                <select name="town" id=" " class="form-select form-control">
                  <option value="">Select Town</option>
                  {% for town in towns %}
                    <option value="{{town.id}}">{{town.town}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="row mb-3">
              <label for="email" class="col-md-4 col-lg-3 col-form-label">Amount</label>
              <div class="col-md-8 col-lg-9">
                <input name="amount" type="number" class="form-control" id="amount" value="" />
              </div>
            </div>
            <div class="mb-3">
              <button name="addTown" class="btn btn-primary" type="submit"><i class="bi bi-plus"></i>Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- End Basic Modal -->
  

myrates/templates/core/modals/secpaymentmodal.html
<div class="modal fade" id="pay" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Payment</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center">
        <h4>Payment Confirmation</h4>
        <p class="instructions">Please go to your M-Pesa account and complete the transaction using the details below:</p>
        <p class="instructions">If you have already paid before,enter the transaction code:</p>
        <p class="instructions">
          <b>PAY BILL Number</b>: <span class="paybill">{{companyDetails.paybill}}</span>
        </p>
        <p class="instructions">
          <b>Account Number</b>: <span class="account"> {{companyDetails.accountno }}</span>
        </p>
        <form action="{% url "core:service_details" application.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="formid" value="paymentupdate" hidden>
          <input type="hidden" name="applicationid" value="{{application.id}}" hidden>
          <div class="row mb-3">
            <label for="formFile" class="col-sm-5 col-form-label">Amount to pay:</label>
            <div class="col-sm-7">
              <input class="form-control" name="amount" type="text" id="amount" required value="{{application.amount}}" readonly/>
            </div>
          </div>
          <div class="row mb-3">
            <label for="formFile" class="col-sm-5 col-form-label">Transaction Code</label>
            <div class="col-sm-7">
              <input class="form-control" name="transactioncode" type="text" id="trxCode" required  />
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <button type="submit" class="btn btn-primary"><i class="bi bi-wallet"></i> Submit</button>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal" aria-label="Close" data-bs-target="#delete-serv">No</button>
      </div>
    </div>
  </div>
</div>