myrates/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("myprofile/", views.ProfileView.as_view(), name="myprofile"),
]

myrates/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("services/",views.OurServices.as_view(),name="services"),
    path("add_services/",views.ServiceAdd.as_view(),name="add_services"),
    path("service_details/<int:servid>",views.ServiceDetails.as_view(),name="service_details"),
    path("service_price/<int:servid>/<int:townid>",views.ServicePrice.as_view(),name="service_price"),
    path("edit_services/<int:servid>",views.ServiceEdit.as_view(),name="edit_services"),
    path("delete_service/<int:servid>",views.ServiceDelete.as_view(),name="delete_service"),
    path("myapplications/",views.ApplicationsListing.as_view(),name="myapplications"),
    path("application_details/<int:aplid>",views.ApplicationDetails.as_view(),name="details"),
    path("applicationsreceived/",views.ApplicationsReceived.as_view(),name="received"),
    path("performance/",views.Dashboard.as_view(),name="performance"),
    path("companyProfile/",views.CompanyDetails.as_view(),name="companyProfile"),
    # requirements
    path("requirements/",views.Requirements.as_view(),name="requirements"),
    # pricing
    path("pricing/",views.Pricing.as_view(),name="pricing"),
    path("payments/",views.PaymentUpdates.as_view(),name="payments"),
    path("application_ui/",views.ApplicationUI.as_view(),name = "application")
] 

myrates/landing/urls.py
from django.urls import path

from . import views

app_name = "landing"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("toc", views.toc, name="toc")
]

myrates/myrates/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("accounts/", include("accounts.urls",namespace="accounts")),
    path("core/", include("core.urls", namespace="core")),
]# + \
#static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #+ \
# static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

myrates/landing/models.py
from django.db import models

# Create your models here.

class FAQ(models.Model):
    question = models.CharField(max_length=200,unique=True)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.question
    
    class Meta:
        ordering = ['created_at']
        
        
class ContactMessage(models.Model):
    name = models.CharField(max_length=255)  # User's name
    mobile = models.CharField(max_length=12)  # User's email
    subject = models.CharField(max_length=255)  # Optional subject
    message = models.TextField()  # Message content
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp for when the message was created

    def __str__(self):
        return f"Message from {self.name} - {self.mobile}"        

myrates/landing/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from core.models import Services, CompanyProfile
from .models import FAQ, ContactMessage

# Create your views here.


class HomeView(View):

    def get(self, request):
        # print(contacts.values())
        company_profiles_dict = [
            {
                "email": profile.email,
                "mobile": profile.mobile,
                "address": profile.address,
                # Add other fields as needed
            }
            for profile in CompanyProfile.objects.all()
        ][0]
        context = {
            "services": Services.objects.all(),
            "faqs": FAQ.objects.all(),
            "contacts": company_profiles_dict,
        }
        return render(request, "landing/home.html", context)

    def post(self, request):
        # check if user is logged in and is admin
        form_data = request.POST
        # print(form_data)
        form_name = form_data["form-name"]
        if (
            request.user.is_authenticated
            and request.user.is_staff
            and form_name != "contactus"
        ):
            if form_name == "add":
                new_faq = FAQ(
                    question=form_data["question"], answer=form_data["answer"]
                )
                new_faq.save()
                return redirect("landing:home")
            elif form_name == "edit":
                # Assuming form_data is a dictionary coming from a form submission
                faq_id = form_data["faq_id"]

                # Step 1: Retrieve the existing FAQ instance
                faq = get_object_or_404(FAQ, id=faq_id)

                # Step 2: Update the fields
                faq.question = form_data["question"]  # Update question
                faq.answer = form_data["answer"]  # Update answer

                # Step 3: Save the changes
                faq.save()

                return redirect("landing:home")
            elif form_name == "delete":
                faq = FAQ.objects.get(id=form_data["faq_id"])
                faq.delete()
                return redirect("landing:home")

        if form_name == "contactus":
            contactus = ContactMessage(
                name=form_data["name"],
                mobile=form_data["mobile"],
                subject=form_data["subject"],
                message=form_data["message"],
            )
            contactus.save()
            return redirect("landing:home")



def toc(request):
    company_profiles_dict = [
            {
                "email": profile.email,
                "mobile": profile.mobile,
                "address": profile.address,
                # Add other fields as needed
            }
            for profile in CompanyProfile.objects.all()
        ][0]
    context = {
           
            "contacts": company_profiles_dict,
        }
    return render(request,"landing/toc.html",context)

myrates/templates/landing/parts/about.html
{% load static %}

<section id="about" class="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 order-1 order-lg-2" data-aos="zoom-in" data-aos-delay="150">
        <img src="{% static 'landing/assets/img/about.jpg' %}" class="img-fluid" alt="" />
      </div>
      <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content" data-aos="fade-right">
        <h3>About Us</h3>
        <p class="fst-italic" style="font-size: 20pt;">
          At Liparates, we are committed to simplifying the property rate payment process for all property owners. 
        </p>
        <p class="fst-italic" style="font-size: 20pt;">
          Our mission is to provide a seamless, secure, and user-friendly solution that saves you time and effort.
        </p>
        <ul>
      
        </ul>
        <a href="#" class="read-more">Read More <i class="bi bi-long-arrow-right"></i></a>
      </div>
    </div>
  </div>
</section>

myrates/templates/landing/parts/contacts.html
<section id="contact" class="contact section-bg">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Contact</h2>
      <p>We’d love to hear from you! Whether you have questions, feedback, or need assistance, our team is here to help. Please fill out the form below, and we’ll respond as soon as possible. Your inquiries are important to us, and we strive to provide prompt and helpful support.</p>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="info-box mb-4">
          <i class="bx bx-map"></i>
          <h3>Our Address</h3>
          <p>{{ contacts.address }}</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="info-box mb-4">
          <i class="bx bx-envelope"></i>
          <h3>Email Us</h3>
          <p>{{ contacts.email }}</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="info-box mb-4">
          <i class="bx bx-phone-call"></i>
          <h3>Call Us</h3>
          <p>0{{ contacts.mobile }}</p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <iframe class="mb-4 mb-lg-0" src="https://www.google.com/maps/place/Chester+House,+09,+Nairobi/@-1.2845745,36.8161169,17z/data=!4m15!1m8!3m7!1s0x182f10d1478145c3:0xf9e7c47247c6e5c8!2sChester+House,+09,+Nairobi!3b1!8m2!3d-1.2845799!4d36.8186918!16s%2Fg%2F12hlxv5lm!3m5!1s0x182f10d1478145c3:0xf9e7c47247c6e5c8!8m2!3d-1.2845799!4d36.8186918!16s%2Fg%2F12hlxv5lm?entry=ttu&g_ep=EgoyMDI0MDkyNC4wIKXMDSoASAFQAw%3D%3D" frameborder="0" style="border:0; width: 100%; height: 257px;" allowfullscreen></iframe>
      </div>

      <div class="col-lg-6">
        <form action="" method="post">
          {% csrf_token %}
          <input type="text" name="form-name" id="" value="contactus" hidden />
          <div class="row">
            <div class="col-md-6 form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required />
            </div>
            <div class="col-md-6 form-group mt-3 mt-md-0">
              <input type="text" class="form-control" name="mobile" id="email" placeholder="Your Mobile Number" required />
            </div>
          </div>
          <div class="form-group mt-3">
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required />
          </div>
          <div class="form-group mt-3">
            <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
          </div>
          {% comment %} <div class="my-3">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your message has been sent. Thank you!</div>
          </div> {% endcomment %}
          <div class="text-center">
            <button type="submit" type="submit" class="btn btn-primary">Send Message</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

myrates/templates/landing/parts/counts.html
{% load static %}
<section id="counts" class="counts">
  <div class="container">
    <div class="row counters">
      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
        <p>Clients</p>
      </div>

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
        <p>Projects</p>
      </div>

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter"></span>
        <p>Hours Of Support</p>
      </div>

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
        <p>Hard Workers</p>
      </div>
    </div>
  </div>
</section>

myrates/templates/landing/parts/faqs.html
<section id="faq" class="faq">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Frequently Asked Questions</h2>
    </div>

    <div class="faq-list">
      <ul>
        {% for faq in faqs %}
          <li data-aos="fade-up" data-aos="fade-up" data-aos-delay="100">
            <i class="bx bx-help-circle icon-help"></i>
            <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1">{{ faq.question }} <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
            <div id="faq-list-1" class="collapse" data-bs-parent=".faq-list">
              <p>{{ faq.answer }}</p>
              {% if user.is_authenticated and user.is_staff %}
                <div class="faq-actions">
                  <div class="row mt-2">
                    <div class="col-md-6 col-lg-6">
                      <a type="button" class="btn btn-primary" href="#" data-toggle="modal" data-target="#edit">Edit</a>
                    </div>
                    <div class="col-md-6 col-lg-6">
                      <a type="button" class="btn btn-danger" href="#" data-toggle="modal" data-target="#delete">Delete</a>
                    </div>
                  </div>
                </div>
                <!-- edit modal -->
                <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="addfaqLabel">Edit FAQ</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      </div>
                      <div class="modal-body">
                        <form action="" method="post">
                          {% csrf_token %}
                          <input type="text" name = "form-name" id="" value="edit"  hidden />
                          <input type="text" name="faq_id" id="" value="{{ faq.id }}"  hidden />
                          <div class="form-group">
                            <label for="questionHelp">Question</label>
                            <input type="text" class="form-control" id="questionHelp" name="question" aria-describedby="questionHelp" placeholder="Enter question" value="{{ faq.question }}" />
                          </div>
                          <div class="form-group">
                            <label for="exampleInputAnswer">Answer</label>
                            <textarea class="form-control" id="answer" name="answer" rows="3">{{ faq.answer }}</textarea>
                          </div>
                          <button type="submit" class="btn btn-primary">Edit FAQ</button>
                        </form>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- delete modal -->
                <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="delete" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="addfaqLabel">DELETE FAQ</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      </div>
                      <div class="modal-body">
                        <p class="mb-2" style="color: red;font-size: 20pt;text-align: center;">Are you sure you want to permanently remove this FAQ?</p>
                        
                        <form action="" method="post" style="align-items: center;" class="text-center">
                          {% csrf_token %}
                          <input type="text" name = "form-name" id="" value="delete"  hidden />
                          <input type="text" name="faq_id" id="" value="{{ faq.id }}"  hidden />
                          <button type="submit" class="btn btn-primary" style="text-align: center;">Yes</button>
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        </form>
                      </div>
                      <div class="modal-footer">
                        
                      </div>
                    </div>
                  </div>
                </div>
              {% endif %}
            </div>
          </li>
        {% endfor %}
      </ul>
      <!-- check if user is logged in and is admin -->
      {% if user.is_authenticated and user.is_staff %}
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addfaq">Add Faq</button>
      {% endif %}
    </div>
  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="addfaq" tabindex="-1" role="dialog" aria-labelledby="addfaq" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addfaqLabel">Add FAQ</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <form action="" method="post">
          {% csrf_token %}
          <input type="text" name = "form-name" id="" value="add"  hidden />
          <div class="form-group">
            <label for="questionHelp">Question</label>
            <input type="text" class="form-control" id="questionHelp" name="question" aria-describedby="questionHelp" placeholder="Enter question" />
          </div>
          <div class="form-group">
            <label for="exampleInputAnswer">Answer</label>
            <textarea class="form-control" id="answer" name="answer" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Save FAQ</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

myrates/templates/landing/parts/features.html
{% load static %}
<section id="features" class="features">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Why Choose us</h2>
      <p>Our platform is designed with your convenience in mind. With a range of features built to simplify and secure your county land rate payments, you can manage everything effortlessly.</p>
    </div>

    <div class="row">
      <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column align-items-lg-center">
        <div class="icon-box mt-5 mt-lg-0" data-aos="fade-up" data-aos-delay="100">
          <i class="bx bx-receipt"></i>
          <h4>Fast & Easy Payments</h4>
          <p>Complete your land rate payments in just a few simple steps, saving you time and effort.</p>
        </div>
        <div class="icon-box mt-5" data-aos="fade-up" data-aos-delay="200">
          <i class="bx bx-cube-alt"></i>
          <h4>Secure Transactions</h4>
          <p>We use advanced encryption to protect your personal data and ensure that every transaction is safe.</p>
        </div>
        <div class="icon-box mt-5" data-aos="fade-up" data-aos-delay="300">
          <i class="bx bx-images"></i>
          <h4>Multi-County Support</h4>
          <p>Manage and pay land rates for multiple counties, all from one convenient platform.</p>
        </div>
        <div class="icon-box mt-5" data-aos="fade-up" data-aos-delay="400">
          <i class="bx bx-shield"></i>
          <h4>24/7 Accessibility</h4>
          <p>Make payments at any time, from anywhere, with no need to visit a county office.</p>
        </div>
      </div>
      <div class="image col-lg-6 order-1 order-lg-2" data-aos="zoom-in" data-aos-delay="100">
        <img src="{% static '/landing/assets/img/features.svg' %}" alt="" class="img-fluid" />
      </div>
    </div>
  </div>
</section>

myrates/templates/landing/parts/footer.html
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Techie</h3>
            <p>
              {{contacts.address}}
              Kenya<br /><br />
              <strong>Phone:</strong> {{contacts.mobile }}<br />
              <strong>Email:</strong> {{contacts.email}}<br />
            </p>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li>
                <i class="bx bx-chevron-right"></i> <a href="#">Home</a>
              </li>
              <li>
                <i class="bx bx-chevron-right"></i> <a href="#about">About us</a>
              </li>
              <li>
                <i class="bx bx-chevron-right"></i> <a href="#services">Services</a>
              </li>
              <li>
                <i class="bx bx-chevron-right"></i> <a href="{% url "landing:toc" %}">Terms of service</a>
              </li>
              <li>
                <i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a>
              </li>
            </ul>
          </div>

          

          <div class="col-lg-5 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            {% comment %} <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p> {% endcomment %}
            <form action="" method="post">
              <input type="email" name="email" />
              <input type="button" value="Subscribe" />
            </form>
          </div>
        </div>
      </div>
    </div>

    {% comment %} <div class="container">
      <div class="copyright-wrap d-md-flex py-4">
        <div class="me-md-auto text-center text-md-start">
          <div class="copyright">
            &copy; Copyright <strong><span>Techie</span></strong>. All Rights Reserved
          </div>
          <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/techie-free-skin-bootstrap-3/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>
    </div> {% endcomment %}
  </footer>

myrates/templates/landing/parts/header.html
{% load static %}
<header id="header" class="fixed-top">
  <div class="container d-flex align-items-center justify-content-between">
    {% comment %} <h1 class="logo"><a href="index.html">Liparates</a></h1> {% endcomment %}
    <!-- Uncomment below if you prefer to use an image logo -->
    <a href="{% url 'landing:home' %}" class="logo"><img src="{% static '/landing/assets/img/logo.png' %}" alt="" class="img-fluid" /></a>
    <nav id="navbar" class="navbar">
      <ul>
        <li>
          <a class="nav-link scrollto active" href="#hero">Home</a>
        </li>
        <li>
          <a class="nav-link scrollto" href="{% url "landing:home" %}#about">About</a>
        </li>
        <li>
          <a class="nav-link scrollto" href="#services">Services</a>
        </li>
        <li>
          <a class="nav-link scrollto" href="#portfolio">Portfolio</a>
        </li>
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>
    <!-- .navbar -->
  </div>
</header>

myrates/templates/landing/parts/hero.html
{% load static %}

<section id="hero" class="d-flex align-items-center">
  <div class="container-fluid" data-aos="fade-up">
    <div class="row justify-content-center">
      <div class="col-xl-5 col-lg-6 pt-3 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
        <h1>Skip the Queue: Pay Land Rates Online!</h1>
        <h2>We solve the puzzle</h2>
        <div>
          <a href="{% url "accounts:login" %}" class="btn-get-started scrollto" target="_blank" >Get Started</a>
        </div>
      </div>
      <div class="col-xl-4 col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="150">
        <img src="{% static '/landing/assets/img/hero-img.png' %}" class="img-fluid animated" alt="" />
      </div>
    </div>
  </div>
</section>

myrates/templates/landing/parts/pricing.html
<section id="pricing" class="pricing section-bg">
    <div class="container" data-aos="fade-up">
      <div class="section-title">
        <h2>Pricing</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row">
        <div class="col-lg-3 col-md-6" data-aos="fade-up" data-aos-delay="100">
          <div class="box">
            <h3>Free</h3>
            <h4><sup>$</sup>0<span>/ month</span></h4>
            <ul>
              <li>Aida dere</li>
              <li>Nec feugiat nisl</li>
              <li>Nulla at volutpat dola</li>
              <li class="na">Pharetra massa</li>
              <li class="na">Massa ultricies mi</li>
            </ul>
            <div class="btn-wrap">
              <a href="#" class="btn-buy">Buy Now</a>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
          <div class="box featured">
            <h3>Business</h3>
            <h4><sup>$</sup>19<span>/ month</span></h4>
            <ul>
              <li>Aida dere</li>
              <li>Nec feugiat nisl</li>
              <li>Nulla at volutpat dola</li>
              <li>Pharetra massa</li>
              <li class="na">Massa ultricies mi</li>
            </ul>
            <div class="btn-wrap">
              <a href="#" class="btn-buy">Buy Now</a>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-4 mt-lg-0" data-aos="fade-up" data-aos-delay="300">
          <div class="box">
            <h3>Developer</h3>
            <h4><sup>$</sup>29<span>/ month</span></h4>
            <ul>
              <li>Aida dere</li>
              <li>Nec feugiat nisl</li>
              <li>Nulla at volutpat dola</li>
              <li>Pharetra massa</li>
              <li>Massa ultricies mi</li>
            </ul>
            <div class="btn-wrap">
              <a href="#" class="btn-buy">Buy Now</a>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-4 mt-lg-0" data-aos="fade-up" data-aos-delay="400">
          <div class="box">
            <span class="advanced">Advanced</span>
            <h3>Ultimate</h3>
            <h4><sup>$</sup>49<span>/ month</span></h4>
            <ul>
              <li>Aida dere</li>
              <li>Nec feugiat nisl</li>
              <li>Nulla at volutpat dola</li>
              <li>Pharetra massa</li>
              <li>Massa ultricies mi</li>
            </ul>
            <div class="btn-wrap">
              <a href="#" class="btn-buy">Buy Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

myrates/templates/landing/parts/services.html
{% load static %}

<section id="services" class="services section-bg">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Services</h2>
      <p style="font-size: 14pt;">
        Easily pay your county land rates from the comfort of your home. 
        Our secure and simple platform saves you time and effort, making compliance quick and stress-free.
      </p>
    </div>

    <div class="row gy-4">
      {% for serv in  services %}
      <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
        <div class="icon-box iconbox-blue">
          <h4><a href="">{{serv.title}}</a></h4>
          <p>{{serv.description}}</p>
        </div>
      </div>
      {% endfor %}

      
    </div>
  </div>
</section>