myrates/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("myprofile/", views.ProfileView.as_view(), name="myprofile"),
]

myrates/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("services/",views.OurServices.as_view(),name="services"),
    path("add_services/",views.ServiceAdd.as_view(),name="add_services"),
    path("service_details/<int:servid>",views.ServiceDetails.as_view(),name="service_details"),
    path("service_price/<int:servid>/<int:townid>",views.ServicePrice.as_view(),name="service_price"),
    path("edit_services/<int:servid>",views.ServiceEdit.as_view(),name="edit_services"),
    path("delete_service/<int:servid>",views.ServiceDelete.as_view(),name="delete_service"),
    path("myapplications/",views.ApplicationsListing.as_view(),name="myapplications"),
    path("application_details/<int:aplid>",views.ApplicationDetails.as_view(),name="details"),
    path("applicationsreceived/",views.ApplicationsReceived.as_view(),name="received"),
    path("performance/",views.Dashboard.as_view(),name="performance"),
    path("companyProfile/",views.CompanyDetails.as_view(),name="companyProfile"),
    # requirements
    path("requirements/",views.Requirements.as_view(),name="requirements"),
    # pricing
    path("pricing/",views.Pricing.as_view(),name="pricing"),
    path("payments/",views.PaymentUpdates.as_view(),name="payments"),
    path("application_ui/",views.ApplicationUI.as_view(),name = "application")
] 

myrates/myrates/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("accounts/", include("accounts.urls",namespace="accounts")),
    path("core/", include("core.urls", namespace="core")),
]# + \
#static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #+ \
# static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

myrates/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Towns(models.Model):
    county = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    municipality = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Services(models.Model):
    title        = models.CharField(max_length=100)
    description  = models.TextField()
    requirements = models.TextField()
    
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class ServiceRequirements(models.Model):
    requirement = models.TextField()
    service     = models.ForeignKey(Services, on_delete=models.CASCADE)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    
class Prices(models.Model):
    service    = models.ForeignKey(Services, on_delete=models.CASCADE)
    town       = models.ForeignKey(Towns, on_delete=models.CASCADE)
    amount     = models.DecimalField(max_digits=10, decimal_places=2)
    approved   = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    
    
class ApplicationRecords(models.Model):
    user                 = models.ForeignKey(User, on_delete=models.CASCADE)
    service              = models.ForeignKey(Services, on_delete=models.CASCADE)
    amount               = models.DecimalField(max_digits=10, decimal_places=2)
    # balance              = models.DecimalField(max_digits=10, decimal_places=2)
    paymentStatus        = models.TextField(max_length=30,choices=[('Pending','Pending'),('Approved','Approved'),('Unpaid','Unpaid'),('Declined','Declined')])
    transactioncode      = models.CharField(max_length=100)
    resolution           = models.TextField(max_length=100,choices=[('New','New'),('Queued','Queued'),('Closed','Closed')])
    remarks              = models.TextField(null=True)
    filesUploaded        = models.CharField(null=True,max_length=1024)
    invoice              = models.CharField(null=True,max_length=1024)
    created_at           = models.DateTimeField(auto_now_add=True)
    updated_at           = models.DateTimeField(auto_now=True)
    
    # def __str__(self):
    #     return self.service
    
    

class ApplicationFiles(models.Model):
    application = models.ForeignKey(ApplicationRecords, on_delete=models.CASCADE)
    file        = models.FileField( upload_to='files/')
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.file
    
    
class CompanyProfile(models.Model):
    name        = models.CharField(max_length=100)
    address     = models.TextField()
    mobile      = models.CharField(max_length=12)
    email       = models.EmailField()
    paybill     = models.CharField(max_length=100)
    accountno   = models.CharField(max_length=100)
    tillno      = models.CharField(max_length=100)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    

class MpesaTransactions(models.Model):
    phone           = models.CharField(max_length=12)
    amount          = models.DecimalField(max_digits=10, decimal_places=2)
    transction_code = models.CharField(max_length=100,unique=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

class Notification(models.Model):
    title       = models.CharField(max_length=100)
    description = models.TextField()
    type        = models.CharField(max_length=100,choices=[('New','New'),('Queued','Queued'),('Closed','Closed')])
    sender      = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

myrates/core/views.py
import os
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin


from accounts.models import Profile
from .models import (
    ApplicationFiles,
    ApplicationRecords,
    CompanyProfile,
    Services,
    ServiceRequirements,
    Towns,
    Prices,
)
from django.core.files.storage import FileSystemStorage

# Create your views here.


class Dashboard(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        enquiries = ApplicationRecords.objects.all()
        context = {
            "total_enquiries": enquiries.count(),
            "new": enquiries.filter(resolution="New").count(),
            "queued": enquiries.filter(resolution="Queued").count(),
            "closed": enquiries.filter(resolution="Closed").count(),
        }
        return render(request, "core/dashboard.html", context)


class Requirements(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def post(self, request):
        requirements = request.POST
        requirement = requirements["requirement"]
        requirement = ServiceRequirements(requirement=requirement)
        requirement.save()
        return redirect("core:add_services")


class OurServices(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        services = Services.objects.all()
        context = {"services": services}
        return render(request, "core/services.html", context)


class ServiceAdd(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        requirements = ServiceRequirements.objects.all()
        context = {"requirements": requirements}
        return render(request, "core/pages/new_service.html", context)

    def post(self, request):
        try:
            service_details = request.POST
            title = service_details["title"]
            description = service_details["description"]
            requirements = service_details["requirement"]
            service = Services(
                title=title, description=description, requirements=requirements
            )
            service.save()
            messages.success(request, "Service added successfully!")
            return redirect("core:services")
        except Exception as e:
            messages.error(request, f"Something went wrong! {e}")
            return render(request, "core/pages/new_service.html")


class ServiceDetails(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid):
        service = Services.objects.get(id=servid)
        towns = Towns.objects.all()
        companyinfo = CompanyProfile.objects.all().last()
        context = {"service": service, "towns": towns, "companyinfo": companyinfo}
        return render(request, "core/pages/service_details.html", context)

    def post(self, request, servid):
        try:
            if request.POST["formid"] == "apply":

                uploadedfiles = request.FILES
                fs = FileSystemStorage()
                uploaded_file_urls = []
                for file in uploadedfiles.keys():
                    file_uploaded = uploadedfiles[file]
                    fileName = f"{file}_{request.user.id}_{servid}_{file_uploaded.name}"
                    fs.save(fileName, file_uploaded)
                    uploaded_file_urls.append(fileName)
                apl = ApplicationRecords(
                    user=User.objects.get(id=request.user.id),
                    service=Services.objects.get(id=servid),
                    amount=request.POST["amount"],
                    paymentStatus="Pending",
                    resolution="New",
                    transactioncode=request.POST["transactioncode"],
                    filesUploaded=",".join(uploaded_file_urls),
                )
                apl.save()
                messages.success(request, "Application submitted successfully!")
                return redirect("core:services")
            elif request.POST["formid"] == "paymentupdate":
                application = ApplicationRecords.objects.get(
                    id=request.POST["applicationid"]
                )
                application.amount = request.POST["amount"]
                application.transactioncode = request.POST["transactioncode"]
                application.save()
                messages.success(request, "Payment details updated successfully!")
                return redirect("core:details", aplid=application.id)
        except Exception as e:
            messages.error(self.request, f"An error occured!{e}")
            return redirect("core:services")


class ServiceEdit(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid):
        service = Services.objects.get(id=servid)
        context = {"service": service}
        return render(request, "core/pages/edit_services.html", context)

    def post(self, request, servid):
        try:
            service_details = request.POST
            title = service_details["title"]
            description = service_details["description"]
            service = Services.objects.get(id=servid)
            service.title = title
            service.description = description
            service.save()
            messages.success(request, "Service updated successfully!")
            return redirect("core:services")
        except Exception as e:
            messages.error(request, f"Something went wrong! {e}")
            return redirect("core:services")


class ServiceDelete(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid):
        try:
            service = Services.objects.get(id=servid)
            service.delete()
            messages.success(request, f"Service delete successfully!")
            return redirect("core:services")
        except Exception as e:
            messages.error(request, f"Error occured!,{e}")
            return redirect("core:services")


class ServicePrice(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, servid, townid):
        try:
            service = Services.objects.get(id=servid)
            town = Towns.objects.get(id=townid)
            price = get_object_or_404(Prices, service=service, town=town)
            context = {"price": price.amount}
            return JsonResponse(context)
        except Exception as e:
            context = {"message": f"Error occured!,{e}"}
            return JsonResponse(context)


class ApplicationsListing(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        try:
            applications = ApplicationRecords.objects.filter(user=request.user)
            if request.user.is_staff:
                applications = ApplicationRecords.objects.all()
            new = applications.filter(paymentStatus="Pending", resolution="New")
            onque = applications.filter(paymentStatus="Paid", resolution="Queued")
            closed = applications.filter(paymentStatus="Paid", resolution="Closed")
            context = {"new": new, "onque": onque, "closed": closed}
            return render(request, "core/myapplications.html", context)
        except Exception as e:
            messages.error(request, f"Error occured!,{e}")
            return HttpResponse(f"Something went wrong! ,{e}")


class ApplicationDetails(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request, aplid):
        application = ApplicationRecords.objects.get(id=aplid)
        profile = Profile.objects.get(user=request.user)
        companyDetails = CompanyProfile.objects.all().last()
        context = {
            "application": application,
            "companyDetails": companyDetails,
            "profile": profile,
        }
        return render(request, "core/application_details.html", context)

    def post(self, request, aplid):
        application = ApplicationRecords.objects.get(id=aplid)
        formdetails = request.POST
        if formdetails["resolution"] in ["Closed", "Queued"]:
            application.resolution = formdetails["resolution"]
            application.paymentStatus = "Paid"
            if "invoice" in request.FILES.keys():
                # upload invoice
                fs = FileSystemStorage()
                file_uploaded = request.FILES["invoice"]
                fileName = f"INVOICE_{request.user.id}_{aplid}_{file_uploaded.name}"
                fs.save(fileName, file_uploaded)
                application.invoice = fileName
            application.save()
            messages.success(request, "Application progress updated successfully!")
            if application.resolution == "Closed":
                # send email to user
                
                messages.success(request, "Application closed successfully!")
            return redirect("core:myapplications")
        else:
            messages.error(request, "Something went wrong!")
            return redirect("core:details", aplid=aplid)


class ApplicationsReceived(LoginRequiredMixin, View):

    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def get(self, request):
        return render(request, "core/applicationsreceived.html")


class Pricing(LoginRequiredMixin, View):

myrates/templates/core/parts/header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'core:performance' %}" class="logo d-flex align-items-center">
      <img src="{% static 'landing/assets/img/logo.png' %}" alt="" />
      {% comment %} <span class="d-none d-lg-block">Liparates</span> {% endcomment %}
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div>
  <!-- End Logo -->

 
  <!-- End Search Bar -->

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <!-- End Search Icon -->

      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-bell"></i>
          <span class="badge bg-primary badge-number"></span>
        </a><!-- End Notification Icon -->

        <!-- End Notification Dropdown Items -->
      </li> {% endcomment %}
      <!-- End Notification Nav -->

      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-chat-left-text"></i>
          <span class="badge bg-success badge-number"></span>
        </a><!-- End Messages Icon -->
        <!-- End Messages Dropdown Items -->
      </li> {% endcomment %}
      <!-- End Messages Nav -->

      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="{% url 'accounts:myprofile' %}">
          <img src="{% static 'images/liparates-user.jpg' %}" alt="Profile" class="rounded-circle" />
          <span class="d-none d-md-block ps-2">{{ user.first_name }}</span>
        </a><!-- End Profile Iamge Icon -->
        <!-- End Profile Iamge Icon -->

        
        <!-- End Profile Dropdown Items -->
      </li>
      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="{% url 'accounts:logout' %}">
          <i class="ri-logout-circle-r-line" style="font-size: 33px;font-weight: bolder;"></i>
        </a>
      </li>
      <!-- End Profile Nav -->
    </ul>
  </nav>
  <!-- End Icons Navigation -->
</header>

myrates/templates/core/parts/invoice_template.html
{% load custom_filters %}
<div class="container">
  <div class="col-md-12">
    <div class="invoice">
      <!-- begin invoice-company -->
      <div class="invoice-company text-inverse f-w-600">
        <span class="pull-right hidden-print">
          <a href="javascript:;" class="btn btn-sm btn-white m-b-10 p-l-5"><i class="fa fa-file t-plus-1 text-danger fa-fw fa-lg"></i> Export as PDF</a>
          <a href="javascript:;" onclick="window.print()" class="btn btn-sm btn-white m-b-10 p-l-5"><i class="fa fa-print t-plus-1 fa-fw fa-lg"></i> Print</a>
        </span>
        {{ companyDetails.name|upper }}
      </div>
      <!-- end invoice-company -->
      <!-- begin invoice-header -->
      <div class="invoice-headerf row">
        <div class="col-sm-12 col-md-4 col-lg-4">
          <small>from</small>
          <address class="m-t-5 m-b-5">
            <strong class="text-inverse">{{ companyDetails.name|title }}</strong><br />
            {{ companyDetails.address|safe }}<br />
            Phone: {{ companyDetails.mobile }}<br />
            Email: {{ companyDetails.email }}
          </address>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4">
          <small>to</small>
          <address class="m-t-5 m-b-5">
            <strong class="text-inverse">{{ application.user.get_full_name }}</strong><br />
            {{ profile.town|safe }}<br />
            Phone: {{ profile.phone }}<br />
            Email: {{ application.user.email }}
          </address>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4">
          <small>Invoice</small>
          <div class="date text-inverse m-t-5">{{ application.created_at }}</div>
          <div class="invoice-detail">
            <em>INV00{{ application.created_at|customDate }}{{ application.id }}</em><br />
          </div>
        </div>
      </div>
      <!-- end invoice-header -->
      <!-- begin invoice-content -->
      <div class="invoice-content">
        <!-- begin table-responsive -->
        <div class="table-responsive">
          <table class="table table-invoice">
            <thead>
              <tr>
                <th>Service Description</th>
                <th class="text-center" width="10%">Qnty</th>
                {% comment %} <th class="text-center" width="10%">HOURS</th> {% endcomment %}
                <th class="text-right" width="20%">TOTAL</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <span class="text-inverse">{{ application.service }}</span><br />
                </td>
                <td class="text-center">1</td>
                <td class="text-right">{{ application.amount }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <!-- end table-responsive -->
        <!-- begin invoice-price -->
        <div class="invoice-price">
          {% comment %} <div class="invoice-price-left">
            <div class="invoice-price-row">
              <div class="sub-price">
                <small>SUBTOTAL</small>
                <span class="text-inverse">$4,500.00</span>
              </div>
              <div class="sub-price">
                <i class="fa fa-plus text-muted"></i>
              </div>
              <div class="sub-price">
                <small>PAYPAL FEE (5.4%)</small>
                <span class="text-inverse">$108.00</span>
              </div>
            </div>
          </div> {% endcomment %}
          <div class="invoice-price-right">
            <small>TOTAL PAYABLE</small> <span class="f-w-600">
              Ksh {{ application.amount }}
            </span>
          </div>
        </div>
        <!-- end invoice-price -->
      </div>
      <!-- end invoice-content -->
      <!-- begin invoice-note -->
      <div class="invoice-note">
        * Payment is due within 5 days working days<br />
        * If you have any questions concerning this invoice, please contact us.
      </div>
      <!-- end invoice-note -->
      <!-- begin invoice-footer -->
      <div class="invoice-footer">
        <p class="text-center m-b-5 f-w-600">THANK YOU FOR YOUR BUSINESS</p>
        <p class="text-center">
          <span class="m-r-10"><i class="fa fa-fw fa-lg fa-globe"></i>{{ companyDetails.name }}</span>
          <span class="m-r-10"><i class="fa fa-fw fa-lg fa-phone-volume"></i> {{ companyDetails.mobile }}</span>
          <span class="m-r-10"><i class="fa fa-fw fa-lg fa-envelope"></i> {{ companyDetails.email }}</span>
        </p>
      </div>
      <!-- end invoice-footer -->
    </div>
  </div>
</div>

myrates/templates/core/parts/sidebar.html
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    {% if user.is_staff %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:performance' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'core:services' %}">
        <i class="bi bi-grid"></i>
        <span>Our Services</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'core:myapplications' %}">
        <i class="bi bi-grid"></i>
        {% if user.is_staff %}
          <span>Applications Received</span>
        {% else %}
          <span>My Applications</span>
        {% endif %}
      </a>
    </li>
    {% if user.is_staff %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:pricing' %}">
          <i class="bi bi-grid"></i>
          <span>Update Pricing</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:companyProfile' %}">
          <i class="bi bi-grid"></i>
          <span>Company Profile</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:payments' %}">
          <i class="bi bi-grid"></i>
          <span>Update Payments</span>
        </a>
      </li>
    {% endif %}

    {% comment %} <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#"><i class="bi bi-menu-button-wide"></i><span>My Applications</span><i class="bi bi-chevron-down ms-auto"></i></a>
      <ul id="components-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
        <li>
          <a href="components-tooltips.html"><i class="bi bi-circle"></i><span>Tooltips</span></a>
        </li>
      </ul>
    </li> {% endcomment %}
    <!-- End Components Nav -->
  </ul>
</aside>